### ISSUE TITLE
Ubuntu support

### ISSUE THREAD

**Issue by daleshaw** [apnex/vmw-cli#1]
vmw-cli doesn't work on Ubuntu (tested on 16.04 LTS with node.js v4.2.6)

I installed packages npm,nodejs (NB: not simply 'node')

/usr/local/bin/vmw-cli expects node.js executable to be named 'node'

Modified vmw-cli to refer to nodejs(1).

Running vmw-cli bombs out with:
```
/usr/local/lib/node_modules/vmw-cli/lib/vmw-cli.js:5
let client = new vmwApi();
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
[...]
```

**Comment by apnex** [comment]
Hi Dale! Unfortunately some linux distributions include older versions of node in the apt-get / yum repos as discussed here: https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
vmw-cli requires at a minimum node.js 8.x to function - and you can follow the instructions above to ugrade on ubuntu. I have made some updates to the readme for clarity.
