### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by msherian** [apnex/vmw-cli#11]
Feature Request: 

Addition of user management would be very helpful
https://my.vmware.com/group/vmware/users-permissions

Especially when there are large numbers of folders
![image](https://user-images.githubusercontent.com/25062092/80228470-00a78500-8647-11ea-869e-251da4a83c6a.png)

**Comment by apnex** [comment]
Due to major website changes, this version is now **DEPRECATED**. Version 2.0 coming soon
