### ISSUE TITLE
NSX-T-242 missing

### ISSUE THREAD

**Issue by r3shin3** [apnex/vmw-cli#12]
hi, 
i can't find and download NSX-T-242 
https://my.vmware.com/group/vmware/details?productId=673&downloadGroup=NSX-T-242
nsx-unified-appliance-2.4.2.0.0.14269551.ova

i already try to download using NSX-T-242 group id but it is not found ..

i check mainindex.json on github also not list NSX-T-242

**Comment by apnex** [comment]
Due to major website changes, this version is now **DEPRECATED**. Version 2.0 coming soon
