### ISSUE TITLE
Is node version 12.x or newer now a requirement?

### ISSUE THREAD

**Issue by GrahamDumpleton** [apnex/vmw-cli#2]
When using node version v10.23.0 one gets an error:

```
(intermediate value).flat is not a function
```

and you can't get list of items under categories such as ``PRODUCT_BINARY``.

```
$ vmw-cli ls vmware_tanzu_kubernetes_grid/1_x/PRODUCT_BINARY
[POST] https://my.vmware.com/channel/api/v1.0/ems/accountinfo
[GET] https://my.vmware.com/channel/public/api/v1.0/products/getProductsAtoZ
[GET] https://my.vmware.com/channel/public/api/v1.0/products/getRelatedDLGList
[CACHE]: TKG-120:988
(intermediate value).flat is not a function
```

The cache file is populated okay, just fails when listing entries in it.

Can also not download files using ``cp`` even when know the name.

The only references can find to that error line for other packages suggest that might need node version 12.x.

So although ``README`` file says node version 8.x or later, is 12.x now required?

**Comment by GrahamDumpleton** [comment]
Confirmed works on node version 15.x.

**Comment by GrahamDumpleton** [comment]
Latest stable version of 14.x works as well.

So suggest perhaps listing minimum node version as 12.x.

**Comment by apnex** [comment]
Thanks Graham - yes indeed it seems one of the dependent modules changed and requires 12. Updating readme for the same. You can always use the docker image if node versions present an issue on your system.
