### ISSUE TITLE
Retrieving previous version

### ISSUE THREAD

**Issue by ErikBussink** [apnex/vmw-cli#2]
When attempting to pull the NSX-T unified-appliance 2.2.0, the vmw-cli index and find only returns the latest version of the product, version 2.3.0, how can we index previous versions ?

**Comment by apnex** [comment]
Hi Erik - if you are performing an index for an entire category - **vmw-cli index vmware-nsx-t-data-center** - you will only get the files that are mapped to this category on my.vmware.com and this is transient as vmware changes the mapped files as new version come out.
There are 2 ways to index other versions of files;
1) index the category the file lives in - i.e nsx-t 2.1 is in **vmware-pivotal-container-service**
2) obtain and directly index the productID: **vmw-cli index NSX-T-220**

The second method is deterministic and will always return nsx-t 2.2 related files even if the categories change. This is the recommended method if you are performing automation and calling vmw-cli from other scripts
