### ISSUE TITLE
Documentation for the my.vmware.com APIs

### ISSUE THREAD

**Issue by vaibhavggarg** [apnex/vmw-cli#3]
Hi, I wanted to work on a script that automatically downloads the latest packages from my.vmware.com, I couldn't find any documentation on the myvmware apis you used in your project. Could you please point me towards that

**Comment by apnex** [comment]
As far as I'm aware - there is no VMware documentation for the APIs I used. The code in this repository is a result of trial and error using Postman interceptor and Chrome Developer tools to interrogate browsers calls to my.vmware.com. If you are looking to write your own scripts and code - take a look at my examples at https://github.com/apnex/vmw-sdk as this could be a good starting point
