### ISSUE TITLE
Support for patch downloads

### ISSUE THREAD

**Issue by ymmit85** [apnex/vmw-cli#7]
Is it possible to add ability to integrate into product patches portal?  https://my.vmware.com/group/vmware/patch#search ?

**Comment by apnex** [comment]
It's certainly 'possible' though I feel vmw-cli should remain focused on GA binaries, and that patching should remain the job of VUM in vCenter

**Comment by apnex** [comment]
Due to major website changes, this version is now DEPRECATED. Version 2.0 coming soon
