### ISSUE TITLE
Sort? Custom Output?

### ISSUE THREAD

**Issue by bzaks1424** [apnex/vmw-cli#9]
Hey there - this is fantastic, but I was wondering if there was a way to basically say "sort by fileDate" or "just show me the filename"  - this way I'm not chaining greps and awks to get everything specifically from your output to drive automation.

Use Case:
I want to be able to automatically run a command that gets me the latest ISO of ESXi 6.7 by either build number or release date. (I could parse the filename if need be). That way I can take that output and instantly chain it to a vmw-cli get <filename> in an unattended fashion.

**Comment by apnex** [comment]
Due to major website changes, this version is now DEPRECATED. Version 2.0 coming soon
